//===============================================================================
//  File Name            : t_vsfx_dut.sv
//  File Revision        : 1.0
//  Date                 : 2013/12/9
//  Author               : wangjie
//  Email                : ycyquick@foxmail.com
//	History				 : 2013/12/9  v1.0 wangjie
//  ----------------------------------------------------------------------------
//  Description      :   fuctional simulation platform				     
//  Function         :   include all c functions
//  ----------------------------------------------------------------------------
// Copyright (c) 2013,Tianjin University.
//               No.92 Weijin Road , Nankai District, Tianjin, 300072, China
// Tianjin University Confidential Proprietary
// ==============================================================================

//===============================================================================

#include "../ISS/PowerPC_ISS_Platform/src/ppc_vector.c"
//vsfx
#include "../ISS/PowerPC_ISS_Platform/src/vaddcuw.c"
#include "../ISS/PowerPC_ISS_Platform/src/vaddsbs.c"
#include "../ISS/PowerPC_ISS_Platform/src/vaddshs.c"
#include "../ISS/PowerPC_ISS_Platform/src/vaddsws.c"
#include "../ISS/PowerPC_ISS_Platform/src/vaddubm.c"
#include "../ISS/PowerPC_ISS_Platform/src/vaddubs.c"
#include "../ISS/PowerPC_ISS_Platform/src/vadduhm.c"
#include "../ISS/PowerPC_ISS_Platform/src/vadduhs.c"
#include "../ISS/PowerPC_ISS_Platform/src/vadduwm.c"
#include "../ISS/PowerPC_ISS_Platform/src/vadduws.c"
#include "../ISS/PowerPC_ISS_Platform/src/vsubcuw.c"
#include "../ISS/PowerPC_ISS_Platform/src/vsubsbs.c"
#include "../ISS/PowerPC_ISS_Platform/src/vsubshs.c"
#include "../ISS/PowerPC_ISS_Platform/src/vsubsws.c"
#include "../ISS/PowerPC_ISS_Platform/src/vsububm.c"
#include "../ISS/PowerPC_ISS_Platform/src/vsububs.c"
#include "../ISS/PowerPC_ISS_Platform/src/vsubuhm.c"
#include "../ISS/PowerPC_ISS_Platform/src/vsubuhs.c"
#include "../ISS/PowerPC_ISS_Platform/src/vsubuwm.c"
#include "../ISS/PowerPC_ISS_Platform/src/vsubuws.c"
#include "../ISS/PowerPC_ISS_Platform/src/vavgsb.c"
#include "../ISS/PowerPC_ISS_Platform/src/vavgsh.c"
#include "../ISS/PowerPC_ISS_Platform/src/vavgsw.c"
#include "../ISS/PowerPC_ISS_Platform/src/vavgub.c"
#include "../ISS/PowerPC_ISS_Platform/src/vavguh.c"
#include "../ISS/PowerPC_ISS_Platform/src/vavguw.c"
#include "../ISS/PowerPC_ISS_Platform/src/vmaxfp.c"
#include "../ISS/PowerPC_ISS_Platform/src/vmaxsb.c"
#include "../ISS/PowerPC_ISS_Platform/src/vmaxsh.c"
#include "../ISS/PowerPC_ISS_Platform/src/vmaxsw.c"
#include "../ISS/PowerPC_ISS_Platform/src/vmaxub.c"
#include "../ISS/PowerPC_ISS_Platform/src/vmaxuh.c"
#include "../ISS/PowerPC_ISS_Platform/src/vmaxuw.c"
#include "../ISS/PowerPC_ISS_Platform/src/vminfp.c"
#include "../ISS/PowerPC_ISS_Platform/src/vminsb.c"
#include "../ISS/PowerPC_ISS_Platform/src/vminsh.c"
#include "../ISS/PowerPC_ISS_Platform/src/vminsw.c"
#include "../ISS/PowerPC_ISS_Platform/src/vminub.c"
#include "../ISS/PowerPC_ISS_Platform/src/vminuh.c"
#include "../ISS/PowerPC_ISS_Platform/src/vminuw.c"
#include "../ISS/PowerPC_ISS_Platform/src/vcmpbfp.c"
#include "../ISS/PowerPC_ISS_Platform/src/vcmpeqfp.c"
#include "../ISS/PowerPC_ISS_Platform/src/vcmpequb.c"
#include "../ISS/PowerPC_ISS_Platform/src/vcmpequh.c"
#include "../ISS/PowerPC_ISS_Platform/src/vcmpequw.c"
#include "../ISS/PowerPC_ISS_Platform/src/vcmpgefp.c"
#include "../ISS/PowerPC_ISS_Platform/src/vcmpgtfp.c"
#include "../ISS/PowerPC_ISS_Platform/src/vcmpgtsb.c"
#include "../ISS/PowerPC_ISS_Platform/src/vcmpgtsh.c"
#include "../ISS/PowerPC_ISS_Platform/src/vcmpgtsw.c"
#include "../ISS/PowerPC_ISS_Platform/src/vcmpgtub.c"
#include "../ISS/PowerPC_ISS_Platform/src/vcmpgtuh.c"
#include "../ISS/PowerPC_ISS_Platform/src/vcmpgtuw.c"
#include "../ISS/PowerPC_ISS_Platform/src/vand.c"
#include "../ISS/PowerPC_ISS_Platform/src/vandc.c"
#include "../ISS/PowerPC_ISS_Platform/src/vnor.c"
#include "../ISS/PowerPC_ISS_Platform/src/vor.c"
#include "../ISS/PowerPC_ISS_Platform/src/vxor.c"
#include "../ISS/PowerPC_ISS_Platform/src/vrlb.c"
#include "../ISS/PowerPC_ISS_Platform/src/vrlh.c"
#include "../ISS/PowerPC_ISS_Platform/src/vrlw.c"
#include "../ISS/PowerPC_ISS_Platform/src/vslb.c"
#include "../ISS/PowerPC_ISS_Platform/src/vslh.c"
#include "../ISS/PowerPC_ISS_Platform/src/vslw.c"
#include "../ISS/PowerPC_ISS_Platform/src/vsrab.c"
#include "../ISS/PowerPC_ISS_Platform/src/vsrah.c"
#include "../ISS/PowerPC_ISS_Platform/src/vsraw.c"
#include "../ISS/PowerPC_ISS_Platform/src/vsrb.c"
#include "../ISS/PowerPC_ISS_Platform/src/vsrh.c"
#include "../ISS/PowerPC_ISS_Platform/src/vsrw.c"
//vcfx
#include "../ISS/PowerPC_ISS_Platform/src/vmhaddshs.c"
#include "../ISS/PowerPC_ISS_Platform/src/vmhraddshs.c"
#include "../ISS/PowerPC_ISS_Platform/src/vmladduhm.c"
#include "../ISS/PowerPC_ISS_Platform/src/vmsummbm.c"
#include "../ISS/PowerPC_ISS_Platform/src/vmsumshm.c"
#include "../ISS/PowerPC_ISS_Platform/src/vmsumshs.c"
#include "../ISS/PowerPC_ISS_Platform/src/vmsumubm.c"
#include "../ISS/PowerPC_ISS_Platform/src/vmsumuhm.c"
#include "../ISS/PowerPC_ISS_Platform/src/vmsumuhs.c"
#include "../ISS/PowerPC_ISS_Platform/src/vmulesb.c"
#include "../ISS/PowerPC_ISS_Platform/src/vmulesh.c"
#include "../ISS/PowerPC_ISS_Platform/src/vmuleub.c"
#include "../ISS/PowerPC_ISS_Platform/src/vmuleuh.c"
#include "../ISS/PowerPC_ISS_Platform/src/vmulosb.c"
#include "../ISS/PowerPC_ISS_Platform/src/vmulosh.c"
#include "../ISS/PowerPC_ISS_Platform/src/vmuloub.c"
#include "../ISS/PowerPC_ISS_Platform/src/vmulouh.c"
#include "../ISS/PowerPC_ISS_Platform/src/vsum2sws.c"
#include "../ISS/PowerPC_ISS_Platform/src/vsum4sbs.c"
#include "../ISS/PowerPC_ISS_Platform/src/vsum4shs.c"
#include "../ISS/PowerPC_ISS_Platform/src/vsum4ubs.c"
#include "../ISS/PowerPC_ISS_Platform/src/vsumsws.c"
//vfpu
#include "../ISS/PowerPC_ISS_Platform/src/vaddfp.c"
#include "../ISS/PowerPC_ISS_Platform/src/vsubfp.c"
#include "../ISS/PowerPC_ISS_Platform/src/vexptefp.c"
#include "../ISS/PowerPC_ISS_Platform/src/vmaddfp.c"
#include "../ISS/PowerPC_ISS_Platform/src/vnmsubfp.c"
#include "../ISS/PowerPC_ISS_Platform/src/vlogefp.c"
#include "../ISS/PowerPC_ISS_Platform/src/vrfim.c"
#include "../ISS/PowerPC_ISS_Platform/src/vrfin.c"
#include "../ISS/PowerPC_ISS_Platform/src/vrfip.c"
#include "../ISS/PowerPC_ISS_Platform/src/vrfiz.c"
#include "../ISS/PowerPC_ISS_Platform/src/vrefp.c"
#include "../ISS/PowerPC_ISS_Platform/src/vrsqrtefp.c"
#include "../ISS/PowerPC_ISS_Platform/src/vcfsx.c"
#include "../ISS/PowerPC_ISS_Platform/src/vcfux.c"
#include "../ISS/PowerPC_ISS_Platform/src/vctsxs.c"
#include "../ISS/PowerPC_ISS_Platform/src/vctuxs.c"
//pu
#include "../ISS/PowerPC_ISS_Platform/src/vmrghb.c"
#include "../ISS/PowerPC_ISS_Platform/src/vmrghh.c"
#include "../ISS/PowerPC_ISS_Platform/src/vmrghw.c"
#include "../ISS/PowerPC_ISS_Platform/src/vmrglb.c"
#include "../ISS/PowerPC_ISS_Platform/src/vmrglh.c"
#include "../ISS/PowerPC_ISS_Platform/src/vmrglw.c"
#include "../ISS/PowerPC_ISS_Platform/src/vperm.c"
#include "../ISS/PowerPC_ISS_Platform/src/vpkpx.c"
#include "../ISS/PowerPC_ISS_Platform/src/vpkshss.c"
#include "../ISS/PowerPC_ISS_Platform/src/vpkshus.c"
#include "../ISS/PowerPC_ISS_Platform/src/vpkswss.c"
#include "../ISS/PowerPC_ISS_Platform/src/vpkswus.c"
#include "../ISS/PowerPC_ISS_Platform/src/vpkuhum.c"
#include "../ISS/PowerPC_ISS_Platform/src/vpkuhus.c"
#include "../ISS/PowerPC_ISS_Platform/src/vpkuwum.c"
#include "../ISS/PowerPC_ISS_Platform/src/vpkuwus.c"
#include "../ISS/PowerPC_ISS_Platform/src/vsel.c"
#include "../ISS/PowerPC_ISS_Platform/src/vsl.c"
#include "../ISS/PowerPC_ISS_Platform/src/vsldoi.c"
#include "../ISS/PowerPC_ISS_Platform/src/vslo.c"
#include "../ISS/PowerPC_ISS_Platform/src/vspltb.c"
#include "../ISS/PowerPC_ISS_Platform/src/vsplth.c"
#include "../ISS/PowerPC_ISS_Platform/src/vspltisb.c"
#include "../ISS/PowerPC_ISS_Platform/src/vspltish.c"
#include "../ISS/PowerPC_ISS_Platform/src/vspltisw.c"
#include "../ISS/PowerPC_ISS_Platform/src/vspltw.c"
#include "../ISS/PowerPC_ISS_Platform/src/vsr.c"
#include "../ISS/PowerPC_ISS_Platform/src/vsro.c"
#include "../ISS/PowerPC_ISS_Platform/src/vupkhpx.c"
#include "../ISS/PowerPC_ISS_Platform/src/vupkhsb.c"
#include "../ISS/PowerPC_ISS_Platform/src/vupkhsh.c"
#include "../ISS/PowerPC_ISS_Platform/src/vupklpx.c"
#include "../ISS/PowerPC_ISS_Platform/src/vupklsb.c"
#include "../ISS/PowerPC_ISS_Platform/src/vupklsh.c"
