./define.v
../../design/src/add_stage.v
../../design/src/align_shf_74.v
../../design/src/csa4_2.v
../../design/src/denorm_handler.v
../../design/src/DW01_csa.v
../../design/src/exp_adjust.v
../../design/src/exp_handler.v
../../design/src/maf.v
../../design/src/mul_24x24.v
../../design/src/mul_stage.v
../../design/src/norm_stage.v
../../design/src/round_stage.v
../../design/src/sign_handler.v
../../design/src/spec_handler.v
../../design/src/sticky_handler.v
../../design/src/unpackage.v
../../design/src/lza_ip/lza_8.v
../../design/src/lza_ip/lza_16.v
../../design/src/lza_ip/lza_32.v
../../design/src/lza_ip/lza_64.v
../../design/src/lza_ip/lza_80.v

../src/vfpu_dc_pkg.sv
../src/vfpu_if.sv
../src/dut_wrapper_m.sv
../src/test_p.sv
../src/top_tb_m.sv
